export const LOGIN_USERS_DETAILS_REQUEST = 'LOGIN_USERS_DETAILS_REQUEST';
export const LOGIN_USERS_DETAILS_SUCCESS = 'LOGIN_USERS_DETAILS_SUCCESS';
export const LOGIN_USERS_DETAILS_FAILURE = 'LOGIN_USERS_DETAILS_FAILURE';

// Static Dropdown Constants
export const GET_ETHNICITY_LIST_REQUEST = 'GET_ETHNICITY_LIST_REQUEST';
export const GET_ETHNICITY_LIST_SUCCESS = 'GET_ETHNICITY_LIST_SUCCESS';
export const GET_ETHNICITY_LIST_FAILURE = 'GET_ETHNICITY_LIST_FAILURE';

// Employee Form Constants
export const EMPLOYEE_FORM_REQUEST = 'EMPLOYEE_FORM_REQUEST';
export const EMPLOYEE_FORM_SUCCESS = 'EMPLOYEE_FORM_SUCCESS';
export const EMPLOYEE_FORM_FAILURE = 'EMPLOYEE_FORM_FAILURE';

export const GET_GENDER_LIST_REQUEST = 'GET_GENDER_LIST_REQUEST';
export const GET_GENDER_LIST_SUCCESS = 'GET_GENDER_LIST_SUCCESS';
export const GET_GENDER_LIST_FAILURE = 'GET_GENDER_LIST_FAILURE';

export const GET_NATIONALITY_LIST_REQUEST = 'GET_NATIONALITY_LIST_REQUEST';
export const GET_NATIONALITY_LIST_SUCCESS = 'GET_NATIONALITY_LIST_SUCCESS';
export const GET_NATIONALITY_LIST_FAILURE = 'GET_NATIONALITY_LIST_FAILURE';

export const GET_CLINICWARD_LIST_REQUEST = 'GET_CLINICWARD_LIST_REQUEST';
export const GET_CLINICWARD_LIST_SUCCESS = 'GET_CLINICWARD_LIST_SUCCESS';
export const GET_CLINICWARD_LIST_FAILURE = 'GET_CLINICWARD_LIST_FAILURE';

export const GET_TITLEPREFIX_LIST_REQUEST = 'GET_TITLEPREFIX_LIST_REQUEST';
export const GET_TITLEPREFIX_LIST_SUCCESS = 'GET_TITLEPREFIX_LIST_SUCCESS';
export const GET_TITLEPREFIX_LIST_FAILURE = 'GET_TITLEPREFIX_LIST_FAILURE';

export const GET_DISCIPLINE_LIST_REQUEST = 'GET_DISCIPLINE_LIST_REQUEST';
export const GET_DISCIPLINE_LIST_SUCCESS = 'GET_DISCIPLINE_LIST_SUCCESS';
export const GET_DISCIPLINE_LIST_FAILURE = 'GET_DISCIPLINE_LIST_FAILURE';

export const GET_SUBDISCIPLINE_LIST_REQUEST = 'GET_SUBDISCIPLINE_LIST_REQUEST';
export const GET_SUBDISCIPLINE_LIST_SUCCESS = 'GET_SUBDISCIPLINE_LIST_SUCCESS';
export const GET_SUBDISCIPLINE_LIST_FAILURE = 'GET_SUBDISCIPLINE_LIST_FAILURE';

export const GET_ORDERSTATUS_LIST_REQUEST = 'GET_ORDERSTATUS_LIST_REQUEST';
export const GET_ORDERSTATUS_LIST_SUCCESS = 'GET_ORDERSTATUS_LIST_SUCCESS';
export const GET_ORDERSTATUS_LIST_FAILURE = 'GET_ORDERSTATUS_LIST_FAILURE';

// Theme Setting Constants
export const THEME_SETTING_DARK = 'THEME_SETTING_DARK';
export const THEME_SETTING_LIGHT = 'THEME_SETTING_LIGHT';

export const GET_COUNTRY = 'GET_COUNTRY';
export const POST_COUNTRY = 'POST_COUNTRY';
export const GET_OFFICE = 'GET_OFFICE';
export const POST_OFFICE = 'POST_OFFICE';
export const GET_BUSINESS = 'GET_BUSINESS';
export const POST_BUSINESS = 'POST_BUSINESS';
export const GET_CONTRACT = 'GET_CONTRACT';
export const POST_CONTRACT = 'POST_CONTRACT';
export const GET_PROJECT_STATUS = 'GET_PROJECT_STATUS';
export const POST_PROJECT_STATUS = 'POST_PROJECT_STATUS';
export const GET_STATUS = 'GET_STATUS';
export const POST_STATUS = 'POST_STATUS';
export const GET_LOCATION = 'GET_LOCATION';
export const POST_LOCATION = 'POST_LOCATION';
export const GET_SERVICEMEN = 'GET_SERVICEMEN';
export const POST_SERVICEMEN = 'POST_SERVICEMEN';

// Invoice List Filters
export const GET_SALESMAN = 'GET_SALESMAN';
export const POST_SALESMAN = 'POST_SALESMAN';
