export const LOGIN_USERS_DETAILS_REQUEST = 'LOGIN_USERS_DETAILS_REQUEST';
export const LOGIN_USERS_DETAILS_SUCCESS = 'LOGIN_USERS_DETAILS_SUCCESS';
export const LOGIN_USERS_DETAILS_FAILURE = 'LOGIN_USERS_DETAILS_FAILURE';

// Static Dropdown Constants
export const GET_ETHNICITY_LIST_REQUEST = 'GET_ETHNICITY_LIST_REQUEST';
export const GET_ETHNICITY_LIST_SUCCESS = 'GET_ETHNICITY_LIST_SUCCESS';
export const GET_ETHNICITY_LIST_FAILURE = 'GET_ETHNICITY_LIST_FAILURE';

export const GET_GENDER_LIST_REQUEST = 'GET_GENDER_LIST_REQUEST';
export const GET_GENDER_LIST_SUCCESS = 'GET_GENDER_LIST_SUCCESS';
export const GET_GENDER_LIST_FAILURE = 'GET_GENDER_LIST_FAILURE';

export const GET_NATIONALITY_LIST_REQUEST = 'GET_NATIONALITY_LIST_REQUEST';
export const GET_NATIONALITY_LIST_SUCCESS = 'GET_NATIONALITY_LIST_SUCCESS';
export const GET_NATIONALITY_LIST_FAILURE = 'GET_NATIONALITY_LIST_FAILURE';

export const GET_CLINICWARD_LIST_REQUEST = 'GET_CLINICWARD_LIST_REQUEST';
export const GET_CLINICWARD_LIST_SUCCESS = 'GET_CLINICWARD_LIST_SUCCESS';
export const GET_CLINICWARD_LIST_FAILURE = 'GET_CLINICWARD_LIST_FAILURE';

export const GET_TITLEPREFIX_LIST_REQUEST = 'GET_TITLEPREFIX_LIST_REQUEST';
export const GET_TITLEPREFIX_LIST_SUCCESS = 'GET_TITLEPREFIX_LIST_SUCCESS';
export const GET_TITLEPREFIX_LIST_FAILURE = 'GET_TITLEPREFIX_LIST_FAILURE';

export const GET_DISCIPLINE_LIST_REQUEST = 'GET_DISCIPLINE_LIST_REQUEST';
export const GET_DISCIPLINE_LIST_SUCCESS = 'GET_DISCIPLINE_LIST_SUCCESS';
export const GET_DISCIPLINE_LIST_FAILURE = 'GET_DISCIPLINE_LIST_FAILURE';

export const GET_SUBDISCIPLINE_LIST_REQUEST = 'GET_SUBDISCIPLINE_LIST_REQUEST';
export const GET_SUBDISCIPLINE_LIST_SUCCESS = 'GET_SUBDISCIPLINE_LIST_SUCCESS';
export const GET_SUBDISCIPLINE_LIST_FAILURE = 'GET_SUBDISCIPLINE_LIST_FAILURE';

export const GET_ORDERSTATUS_LIST_REQUEST = 'GET_ORDERSTATUS_LIST_REQUEST';
export const GET_ORDERSTATUS_LIST_SUCCESS = 'GET_ORDERSTATUS_LIST_SUCCESS';
export const GET_ORDERSTATUS_LIST_FAILURE = 'GET_ORDERSTATUS_LIST_FAILURE';
